// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmxqspxuirwndaghxeyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFteHFzcHh1aXJ3bmRhZ2h4ZXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MjY3MTQsImV4cCI6MjA2NDEwMjcxNH0.cWlvDvgUnegDuoh4yY2sat9be4Ru4V_3jZq_7Z1vUWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);